version: '3.8'

services:
  api:
    container_name: livestock-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Server=${DB_HOST},1433;Database=${DB_NAME};User Id=${DB_USER};Password=${DB_PASS};
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on: []
    restart: always
